version: '3'

services:
  auth-authorization-service-web:
    build: .
    environment:
      IS_LOCAL: 0
      IS_STAGING: 0
      IS_PRODUCTION: 1
      DB_NAME: innovo_builders_authorization
      DB_USER: postgres
      DB_PASS: hralE8xNal9BxLfP
      DB_HOST: 34.66.141.123
      DB_PORT: 5432
    image: gcr.io/innovo-app/innovo_builder_microservice_auth_authorization:latest
    command: /bin/sh -c "python3 /code/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8001:8000
    restart: always
