version: '3'

services:
  auth-authorization-service-web:
    build: .
    environment:
      IS_LOCAL: 0
      IS_STAGING: 0
      IS_PRODUCTION: 1
      DB_NAME: <DB_NAME>
      DB_USER: <username>
      DB_PASS: <pass>
      DB_HOST: <host>
      DB_PORT: 5432
    image: gcr.io/innovo-app/innovo_builder_microservice_auth_authorization:latest
    command: /bin/sh -c "python3 /code/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8001:8000
    restart: always
